### ISSUE TITLE
Swift 2.3 support - branch missing?

### ISSUE THREAD

**Issue by alpennec** [duemunk/Async#89]
Hello,
I can't find any branch for iOS Swift 2.3.
Is is possible to have one so we can start migrating Async to Swift 2.3 (+ use it in our projects with Carthage and CocoaPods).
Thanks,
Axel

**Comment by duemunk** [comment]
I haven't tested, but what fails in Async on Swift 2.3?

**Comment by alpennec** [comment]
Ok my bad, it's actually working with Carthage.

**Comment by duemunk** [comment]
Ok that's what I had expected, but never actually tested it :)

**Comment by alpennec** [comment]
Actually the framework can't be built using Carthage and Xcode 8 beta 6 / Swift 2.3. Even if the code does not have any issue, the project settings needs to be updated (migrated) to Swift 2.3. Can you have a look please @duemunk please? Thanks!

**Comment by vCrespoP** [comment]
+1 Getting this

**Comment by lexrus** [comment]
Here is the branch: https://github.com/duemunk/Async/tree/feature/Swift_2.3
You can checkout this branch with Carthage:
``` ruby
github "duemunk/Async" "feature/Swift_2.3"
```

I've added a tag 1.7.4, but haven't pushed it to CocoaPods trunk. @duemunk could you push it?

**Comment by duemunk** [comment]
@lexrus I've tried to push the 2.3 branch to the CocoaPods Trunk now, but I get the same error as for my 3.0 branch. Haven't found the solution yet. Any help highly appreciated!

```console
== CLEAN TARGET AsyncSwift OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET AsyncSwift OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
 -> AsyncSwift (1.7.4)
    - ERROR | xcodebuild: Returned an unsuccessful exit code.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:111:in `validate_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:61:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by duemunk** [comment]
1.7.4 is pushed to CocoaPods Trunk now.
